def checkbox(name: str, label: str, section: str = "Checklist"):
    return {"name": name, "label": label, "type": "checkbox", "required": True, "section": section}


def text(name: str, label: str, section: str = "Checklist"):
    return {"name": name, "label": label, "type": "text", "required": True, "section": section}


def number(name: str, label: str, section: str = "Checklist"):
    return {"name": name, "label": label, "type": "number", "required": True, "section": section}


FORM_CONFIGS = {
    "mindray8am": {
        "title": "Mindray BC 780 - 8AM",
        "table": "mindraybc",
        "timerec": "eightam",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": {
            "one": "one",
            "two": "two",
            "three": "three",
            "four": "four",
            "five": "five",
            "six": "six",
            "seven": "seven",
            "eight": "eight",
            "nine": "nine",
        },
        "fields": [
            checkbox("one", "1. Check & Empty Liquid Waste"),
            text("two", "2. % Quantity of DS Diluent"),
            text("three", "3. % Quantity of M-6LH LYSE"),
            text("four", "4. % Quantity of M-6LD LYSE"),
            text("five", "5. % Quantity of M-6FD DYE"),
            text("six", "6. % Quantity of ESR SOLUTION"),
            text("seven", "7. % Quantity of Probe Cleanser"),
            checkbox("eight", "8. Run Controls"),
            checkbox("nine", "9. Machine Cleaning & Dusting"),
        ],
    },
    "mindraybc7008am": {
        "title": "Mindray BC 700 - 8AM",
        "table": "mindraybc700",
        "timerec": "eightam",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": {
            "one": "one",
            "two": "two",
            "three": "three",
            "four": "four",
            "five": "five",
            "six": "six",
            "seven": "seven",
            "nine": "nine",
        },
        "fields": [
            checkbox("one", "1. Check & Empty Liquid Waste"),
            text("two", "2. % Quantity of DS Diluent"),
            text("three", "3. % Quantity of M-6LH LYSE"),
            text("four", "4. % Quantity of M-6LD LYSE"),
            text("five", "5. % Quantity of M-6FD DYE"),
            text("six", "6. % Quantity of ESR SOLUTION"),
            text("seven", "7. % Quantity of Probe Cleanser"),
            checkbox("nine", "9. Machine Cleaning & Dusting"),
        ],
    },
    "mindray4pm": {
        "title": "Mindray BC 780 - 4PM",
        "table": "mindraybc",
        "timerec": "fourpm",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": {
            "one": "one",
            "two": "two",
        },
        "fields": [
            checkbox("one", "1. Check & Empty Liquid Waste"),
            checkbox("two", "2. Run Controls"),
        ],
    },
    "cobaspure8am": {
        "title": "Roche Cobas Pure - 8AM",
        "table": "cobaspure",
        "timerec": "eightam",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": {
            "one": "chemistry",
            "two": "immunoassay",
            "three": "consumablech",
            "four": "consumableimm",
            "five": "chimm",
            "six": "cleandust",
            "seven": "waterplant",
            "eight": "boardreagent",
            "nine": "tds",
            "ten": "conductivity",
            "eleven": "one",
            "twelve": "two",
            "thirteen": "three",
            "fourteen": "four",
            "fifteen": "five",
            "sixteen": "six",
            "seventeen": "seven",
            "eightteen": "eight",
            "ninteen": "nine",
            "twenty": "ten",
            "lampremaining": "lampremaining",
            "cellremaining": "cellremaining",
            "twentyone": "eleven",
            "twentytwo": "twelve",
            "twentythree": "thirteen",
            "twentyfour": "fourteen",
        },
        "fields": [
            checkbox("one", "1. Check & Empty Liquid Waste (Chemistry)", "Main"),
            checkbox("two", "2. Check & Empty Liquid Waste (Immunoassay)", "Main"),
            checkbox("three", "3. Check Consumable of Chemistry (As per List)", "Main"),
            checkbox("four", "4. Check Consumable of Immunoassay (As per List)", "Main"),
            checkbox("five", "5. Run Controls of Both Chemistry & Immunoassay", "Main"),
            checkbox("six", "6. Machine Cleaning & Dusting", "Main"),
            checkbox("seven", "7. Check RO & DI Water Plant Reservoirs", "Main"),
            checkbox("eight", "8. Check Inventory of On Board Reagents", "Main"),
            text("nine", "9. RO Tank TDS (<30)", "Main"),
            text("ten", "10. DI Tank Conductivity (<2)", "Main"),
            checkbox("eleven", "1. ISE Reference Electrolyte", "ISE"),
            checkbox("twelve", "2. ISE Diluent", "ISE"),
            checkbox("thirteen", "3. ISE Internal Standard", "ISE"),
            checkbox("fourteen", "4. ISE Cleaning Solution/SysClean", "ISE"),
            checkbox("fifteen", "5. Activator", "ISE"),
            checkbox("sixteen", "1. Basic Wash", "C-303"),
            checkbox("seventeen", "2. Acid Wash", "C-303"),
            checkbox("eightteen", "3. EcoTergent", "C-303"),
            checkbox("ninteen", "4. NaOHD", "C-303"),
            checkbox("twenty", "5. SMS", "C-303"),
            text("lampremaining", "6. Lamp Remaining Hours", "C-303"),
            text("cellremaining", "7. Cell Remaining Days", "C-303"),
            checkbox("twentyone", "1. PreClean IIM", "E-402"),
            checkbox("twentytwo", "2. ProCellllM", "E-402"),
            checkbox("twentythree", "3. ASSYCUPS/TIPS", "E-402"),
            checkbox("twentyfour", "4. Clean Cell", "E-402"),
        ],
    },
    "cobaspure7pm": {
        "title": "Roche Cobas Pure - 7PM",
        "table": "cobaspure",
        "timerec": "sevenpm",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": {
            "one": "chemistry",
            "two": "immunoassay",
            "three": "consumablech",
            "four": "consumableimm",
            "five": "chimm",
            "six": "cleandust",
            "seven": "waterplant",
            "eight": "boardreagent",
            "nine": "one",
            "ten": "two",
            "eleven": "three",
            "twelve": "four",
            "thirteen": "five",
            "fourteen": "six",
            "fifteen": "seven",
            "sixteen": "eight",
            "seventeen": "nine",
            "eightteen": "ten",
            "ninteen": "eleven",
            "twenty": "twelve",
            "twentyone": "thirteen",
            "twentytwo": "fourteen",
            "twentythree": "fifteen",
            "twentyfour": "sixteen",
            "twentyfive": "seventeen",
            "twentysix": "eighteen",
            "twentyseven": "nineteen",
            "twentyeight": "twenty",
            "twentynine": "twentyone",
            "thirty": "twentytwo",
            "thirtyone": "twentythree",
            "thirtytwo": "twentyfour",
        },
        "fields": [
            checkbox("one", "1. Check & Empty Liquid Waste (Chemistry)", "Main"),
            checkbox("two", "2. Check & Empty Liquid Waste (Immunoassay)", "Main"),
            checkbox("three", "3. Check Consumable of Chemistry (As per List)", "Main"),
            checkbox("four", "4. Check Consumable of Immunoassay (As per List)", "Main"),
            checkbox("five", "5. Run Controls of Both Chemistry & Immunoassay", "Main"),
            checkbox("six", "6. Machine Cleaning & Dusting", "Main"),
            checkbox("seven", "7. Check RO & DI Water Plant Reservoirs", "Main"),
            checkbox("eight", "8. Check Inventory of On Board Reagents", "Main"),
            checkbox("nine", "1. ISE Reference Electrolyte", "ISE"),
            checkbox("ten", "2. ISE Diluent", "ISE"),
            checkbox("eleven", "3. ISE Internal Standard", "ISE"),
            checkbox("twelve", "4. ISE Cleaning Solution/SysClean", "ISE"),
            checkbox("thirteen", "5. Activator", "ISE"),
            checkbox("fourteen", "6. Na Electrode", "ISE"),
            checkbox("fifteen", "7. K Electrode", "ISE"),
            checkbox("sixteen", "8. CL Electrode", "ISE"),
            checkbox("seventeen", "9. REFERENCE ELECTRODE", "ISE"),
            checkbox("eightteen", "1. Basic Wash", "C-303"),
            checkbox("ninteen", "2. Acid Wash", "C-303"),
            checkbox("twenty", "3. EcoTergent", "C-303"),
            checkbox("twentyone", "4. NaOHD", "C-303"),
            checkbox("twentytwo", "5. SMS", "C-303"),
            checkbox("twentythree", "6. SCCS", "C-303"),
            checkbox("twentyfour", "7. S12 [SAMPLE INDEX]", "C-303"),
            checkbox("twentyfive", "8. NACL9%", "C-303"),
            checkbox("twentysix", "9. HbA1c Hemolyzing Reagent", "C-303"),
            checkbox("twentyseven", "10. LAMP HALOGEN", "C-303"),
            checkbox("twentyeight", "11. Reaction Cell for C-303", "C-303"),
            checkbox("twentynine", "1. PreClean IIM", "E-402"),
            checkbox("thirty", "2. ProCellllM", "E-402"),
            checkbox("thirtyone", "3. ASSYCUPS/TIPS", "E-402"),
            checkbox("thirtytwo", "4. Clean Cell", "E-402"),
        ],
    },
    "cobaspure130am": {
        "title": "Roche Cobas Pure - 1:30AM",
        "table": "cobaspure",
        "timerec": "onethirtyam",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": {
            "one": "chemistry",
            "two": "immunoassay",
            "three": "consumablech",
            "four": "consumableimm",
            "five": "chimm",
            "six": "cleandust",
            "seven": "waterplant",
            "eight": "boardreagent",
            "nine": "tds",
            "eleven": "one",
            "twelve": "two",
            "thirteen": "three",
            "fourteen": "four",
            "fifteen": "five",
            "sixteen": "six",
            "seventeen": "seven",
            "eightteen": "eight",
            "ninteen": "nine",
            "twenty": "ten",
            "twentyone": "eleven",
            "twentytwo": "twelve",
            "twentythree": "thirteen",
            "twentyfour": "fourteen",
        },
        "fields": [
            checkbox("one", "1. Check & Empty Liquid Waste (Chemistry)", "Main"),
            checkbox("two", "2. Check & Empty Liquid Waste (Immunoassay)", "Main"),
            checkbox("three", "3. Check Consumable of Chemistry (As per List)", "Main"),
            checkbox("four", "4. Check Consumable of Immunoassay (As per List)", "Main"),
            checkbox("five", "5. Check RO & DI Water Plant Reservoirs", "Main"),
            checkbox("six", "6. Check ECO-D & NAOHD on Board", "Main"),
            checkbox("seven", "7. Check ISE Reference/Internal/Diluent", "Main"),
            checkbox("eight", "8. Dispense 500 ul of ISE Standard Low/High", "Main"),
            checkbox("nine", "9. Start & Complete Daily Maintenance", "Main"),
            checkbox("eleven", "1. ISE Reference Electrolyte", "ISE"),
            checkbox("twelve", "2. ISE Diluent", "ISE"),
            checkbox("thirteen", "3. ISE Internal Standard", "ISE"),
            checkbox("fourteen", "4. ISE Cleaning Solution/SysClean", "ISE"),
            checkbox("fifteen", "5. Activator", "ISE"),
            checkbox("sixteen", "1. Basic Wash", "C-303"),
            checkbox("seventeen", "2. Acid Wash", "C-303"),
            checkbox("eightteen", "3. EcoTergent", "C-303"),
            checkbox("ninteen", "4. NaOHD", "C-303"),
            checkbox("twenty", "5. SMS", "C-303"),
            checkbox("twentyone", "1. PreClean IIM", "E-402"),
            checkbox("twentytwo", "2. ProCellllM", "E-402"),
            checkbox("twentythree", "3. ASSYCUPS/TIPS", "E-402"),
            checkbox("twentyfour", "4. Clean Cell", "E-402"),
        ],
    },
    "attalica8am": {
        "title": "Attalica - 8AM",
        "table": "attalica",
        "timerec": "eightam",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": {
            "one": "chemistry",
            "two": "consumablech",
            "three": "consumableimm",
            "four": "chimm",
            "five": "cleandust",
            "six": "waterplant",
            "seven": "tds",
            "eight": "conductivity",
            "nine": "one",
            "ten": "two",
            "eleven": "three",
            "twelve": "four",
            "thirteen": "five",
            "fourteen": "six",
            "fifteen": "seven",
            "sixteen": "eight",
            "seventeen": "nine",
            "eighteen": "ten",
            "nineteen": "eleven",
            "twenty1": "twelve",
            "twentyone": "thirteen",
        },
        "fields": [
            checkbox("one", "1. Check Empty Solid Waste", "Main"),
            checkbox("two", "2. Check Consumable of Chemistry", "Main"),
            checkbox("three", "3. Check Consumable of Immunoassay", "Main"),
            checkbox("four", "4. Run Controls of Both Chemistry & Immunoassay", "Main"),
            checkbox("five", "5. Machine Cleaning & Dusting", "Main"),
            checkbox("six", "6. Check RO & DI Water Plant Reservoirs", "Main"),
            text("seven", "7. RO Tank TDS", "Main"),
            text("eight", "8. DI Tank Conductivity", "Main"),
            text("nine", "1. IM Acid", "IM"),
            text("ten", "2. IM Base", "IM"),
            text("eleven", "3. IM Cleaner", "IM"),
            text("twelve", "4. IM WashSS", "IM"),
            text("thirteen", "1. CH Cleaner", "CH"),
            text("fourteen", "2. CH Conditioner", "CH"),
            text("fifteen", "3. CH Wash", "CH"),
            text("sixteen", "4. CH Diluent", "CH"),
            checkbox("seventeen", "5. RPC-1", "CH"),
            checkbox("eighteen", "6. RPC-2", "CH"),
            checkbox("nineteen", "7. RPC-4", "CH"),
            checkbox("twenty1", "8. WBA", "CH"),
            text("twentyone", "9. Lamp Coolant", "CH"),
        ],
    },
    "attalica7pm": {
        "title": "Attalica - 7PM",
        "table": "attalica",
        "timerec": "sevenpm",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": "__same_as_attalica8am__",
        "fields": "__same_as_attalica8am__",
    },
    "attalica12am": {
        "title": "Attalica - 12:30AM",
        "table": "attalica",
        "timerec": "twelvethirtyam",
        "datetime_column": "datetime",
        "username_column": "username",
        "submitform": 1,
        "column_map": "__same_as_attalica8am__",
        "fields": "__same_as_attalica8am__",
    },
    "aclelite": {
        "title": "ACL Elite - 8AM",
        "table": "aclelite",
        "timerec": "eightam",
        "datetime_column": "datetimess",
        "username_column": "username",
        "submitform": None,
        "column_map": {
            "one": "cleaningcycle",
            "two": "rinsewater",
            "three": "cleanb",
            "four": "rwash",
            "five": "cleana",
            "six": "ptreagent",
            "seven": "apttreq",
            "eight": "machinedus",
        },
        "fields": [
            checkbox("one", "1. Cleaning Cycle", "Main"),
            checkbox("two", "2. Rinse Waste Reservoir", "Main"),
            checkbox("three", "3. Clean B Change", "Main"),
            checkbox("eight", "4. Machine Dusting", "Main"),
            checkbox("four", "5. R Wash", "Inventory"),
            checkbox("five", "6. Clean A", "Inventory"),
            checkbox("six", "7. PT Reagent", "Inventory"),
            checkbox("seven", "8. APTT Reagent", "Inventory"),
        ],
    },
    "lifotronic_daily": {
        "title": "DAILY MAINTENANCE LOGSHEET - LIFOTRONIC H100",
        "table": "lifotronic_h100_daily",
        "timerec": None,
        "datetime_column": "datetime",
        "username_column": "documentedby",
        "submitform": None,
        "fixed_columns": {
            "approvedby": "Pending",
        },
        "column_map": {
            "reagent_volume_check": "reagent_volume_check",
            "check_rt": "check_rt",
            "column_count": "column_count",
            "filter_count": "filter_count",
            "adc_check": "adc_check",
            "pressure_check": "pressure_check",
        },
        "fields": [
            checkbox("reagent_volume_check", "Reagent Volume Check", "Checklist"),
            checkbox("check_rt", "Check RT", "Checklist"),
            number("column_count", "Column Count", "Checklist"),
            number("filter_count", "Filter Count", "Checklist"),
            checkbox("adc_check", "ADC Check", "Checklist"),
            checkbox("pressure_check", "Pressure Check", "Checklist"),
        ],
    },
    "lifotronic_weekly": {
        "title": "WEEKLY MAINTENANCE LOGSHEET - LIFOTRONIC H100",
        "table": "lifotronic_h100_weekly",
        "timerec": None,
        "datetime_column": "datetime",
        "username_column": "documentedby",
        "submitform": None,
        "fixed_columns": {
            "approvedby": "Pending",
        },
        "column_map": {
            "hp_pump_cleaning": "hp_pump_cleaning",
            "diluting_tank_cleaning": "diluting_tank_cleaning",
            "probe_inner_well": "probe_inner_well",
            "probe_outer_well": "probe_outer_well",
            "clean_system": "clean_system",
            "clean_sample_rack": "clean_sample_rack",
            "clean_sample_holder": "clean_sample_holder",
        },
        "fields": [
            checkbox("hp_pump_cleaning", "HP Pump Cleaning", "Checklist"),
            checkbox("diluting_tank_cleaning", "Diluting Tank Cleaning", "Checklist"),
            checkbox("probe_inner_well", "Probe Inner Well", "Checklist"),
            checkbox("probe_outer_well", "Probe Outer Well", "Checklist"),
            checkbox("clean_system", "Clean System", "Checklist"),
            checkbox("clean_sample_rack", "Clean Sample Rack", "Checklist"),
            checkbox("clean_sample_holder", "Clean Sample Holder", "Checklist"),
        ],
    },
    "laurav2_daily": {
        "title": "LAURA V2 - Daily Maintenance",
        "panel_subtitle": "Equipment: LAURA V2",
        "table": "laurav2_daily",
        "timerec": None,
        "datetime_column": "datetime",
        "username_column": "documentedby",
        "submitform": None,
        "fixed_columns": {
            "approvedby": "Pending",
        },
        "column_map": {
            "cleaning_of_sensor": "cleaning_of_sensor",
            "disposal_of_waste_strips": "disposal_of_waste_strips",
            "wiping_of_screen": "wiping_of_screen",
            "cleaning_of_belt": "cleaning_of_belt",
        },
        "fields": [
            checkbox("cleaning_of_sensor", "Cleaning of sensor", "Daily Maintenance"),
            checkbox("disposal_of_waste_strips", "Disposal of waste strips", "Daily Maintenance"),
            checkbox("wiping_of_screen", "Wiping of the screen", "Daily Maintenance"),
            checkbox("cleaning_of_belt", "Cleaning of belt", "Daily Maintenance"),
        ],
    },
    "laurav2_weekly": {
        "title": "LAURA V2 - Weekly Maintenance",
        "panel_subtitle": "Equipment: LAURA V2",
        "table": "laurav2_weekly",
        "timerec": None,
        "datetime_column": "datetime",
        "username_column": "documentedby",
        "submitform": None,
        "fixed_columns": {
            "approvedby": "Pending",
        },
        "column_map": {
            "waste_bin_cleaning": "waste_bin_cleaning",
            "equipment_cleaning": "equipment_cleaning",
        },
        "fields": [
            checkbox("waste_bin_cleaning", "Waste bin Cleaning", "Weekly Maintenance"),
            checkbox("equipment_cleaning", "Equipment Cleaning", "Weekly Maintenance"),
        ],
    },
}

# Reuse Attalica mapping and fields for all Attalica time variants.
FORM_CONFIGS["attalica7pm"]["column_map"] = FORM_CONFIGS["attalica8am"]["column_map"]
FORM_CONFIGS["attalica7pm"]["fields"] = FORM_CONFIGS["attalica8am"]["fields"]
FORM_CONFIGS["attalica12am"]["column_map"] = FORM_CONFIGS["attalica8am"]["column_map"]
FORM_CONFIGS["attalica12am"]["fields"] = FORM_CONFIGS["attalica8am"]["fields"]


NAV_ITEMS = [
    {
        "label": "Mindray",
        "children": [
            {"label": "8AM Form", "endpoint": "main.mindray8am"},
            {"label": "4PM Form", "endpoint": "main.mindray4pm"},
            {"label": "Verification", "endpoint": "main.mindrayverification"},
        ],
    },
    {
        "label": "Mindray BC 700",
        "children": [
            {"label": "8AM Form", "endpoint": "main.mindraybc7008am"},
            {"label": "Verification", "endpoint": "main.mindraybc700verification"},
        ],
    },
    {
        "label": "Cobas Pure",
        "children": [
            {"label": "8AM Form", "endpoint": "main.cobaspure8am"},
            {"label": "7PM Form", "endpoint": "main.cobaspure7pm"},
            {"label": "1:30AM Form", "endpoint": "main.cobaspure130am"},
            {"label": "Verification", "endpoint": "main.cobaspureall"},
        ],
    },
    {
        "label": "Attalica",
        "children": [
            {"label": "8AM Form", "endpoint": "main.attalica8am"},
            {"label": "7PM Form", "endpoint": "main.attalica7pm"},
            {"label": "12:30AM Form", "endpoint": "main.attalica12am"},
            {"label": "Verification", "endpoint": "main.attalicaverification"},
        ],
    },
    {
        "label": "ACL Elite",
        "children": [
            {"label": "8AM Form", "endpoint": "main.aclelite"},
            {"label": "Verification", "endpoint": "main.aclelitemaint"},
        ],
    },
    {
        "label": "LIFOTRONIC H100",
        "children": [
            {"label": "9 AM", "endpoint": "main.lifotronic_daily_form"},
            {"label": "Weekly Form", "endpoint": "main.lifotronic_weekly_form"},
            {"label": "Verification", "endpoint": "main.lifotronicverification"},
        ],
    },
    {
        "label": "LAURA V2",
        "children": [
            {"label": "9 AM", "endpoint": "main.laurav2_daily_form"},
            # {"label": "Weekly Form", "endpoint": "main.laurav2_weekly_form"},  # disabled for now
            {"label": "Verification", "endpoint": "main.laurav2_verification"},
        ],
    },
]


TIME_LABELS = {
    "eightam": "8 AM",
    "fourpm": "4 PM",
    "sevenpm": "7 PM",
    "onethirtyam": "1:30 AM",
    "twelveam": "12AM",
    "twelvethirtyam": "12:30 AM",
}

